name: CI Builds

on: [push]

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true  # Fetches all submodules
      - uses: actions/setup-java@v5
        with:
          distribution: 'graalvm' # See 'Supported distributions' for available options
          java-version: '25'
      - name: Maven build
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw --batch-mode --no-transfer-progress clean test verify site properties:read-project-properties sonar:sonar -Pjacoco -Psonar --file pom.xml

      - name: Get Maven project version
        id: get_version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: E2E Test
        env:
          CURSOR_API_KEY: ${{ secrets.CURSOR_API_KEY }}
        run: |
          java -jar churrera-cli/target/churrera-cli-${{ steps.get_version.outputs.VERSION }}.jar run \
          --workflow churrera-cli/src/test/resources/examples/hello-world-bash/workflow-hello-world.xml \
          --delete-on-success-completion --polling-interval 10

      - name: Upload jar
        uses: actions/upload-artifact@v5
        with:
          name: churrera-cli-${{ steps.get_version.outputs.VERSION }}.jar
          path: |
            ./churrera-cli/target/churrera-cli-${{ steps.get_version.outputs.VERSION }}.jar
